name: AME
favicon: null
layout_spectrum: 0.06401
typography_spectrum: 0.15523
title: AME Cloud Ventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#919191'
    - '#b1b1b1'
    - '#ffffff'
    - '#727272'
    - '#323232'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
