name: AME
favicon: null
layout_spectrum: 0.1423295463901013
typography_spectrum: 0.6041279844939709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.7196807223372161
  rhythmicContrast: 0.5929712906945497
purpose: []
