name: AME
favicon: null
layout_spectrum: 0.1423295463901013
typography_spectrum: 0.15523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#919191'
    - '#b1b1b1'
    - '#ffffff'
    - '#727272'
    - '#323232'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
